<a href="https://colab.research.google.com/github/sftSalman/pytorchFundamental/blob/main/fundamental_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [7]:
scalar = torch.tensor(6)

In [8]:
scalar

tensor(6)

In [10]:
ex = torch.tensor([[1,2,3,4],[2,3,44,3]])

In [11]:
ex

tensor([[ 1,  2,  3,  4],
        [ 2,  3, 44,  3]])

In [12]:
ex2 = torch.tensor([[1,2,3,4],[2,3,44,3]],dtype=float)

In [13]:
ex2

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3., 44.,  3.]], dtype=torch.float64)

In [15]:
ex.ndim

2

In [16]:
ex2.shape

torch.Size([2, 4])

In [17]:
random_tensor= torch.rand(size=(2,2))

In [18]:
random_tensor

tensor([[0.5229, 0.2760],
        [0.7964, 0.3062]])

In [19]:
ones = torch.ones(size=(45,45))

In [20]:
ones

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [21]:
zeros = torch.zeros(size=(45,45))

In [22]:
zeros

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [24]:
#creating range

In [27]:
one_to_ten = torch.arange(start=0,end=10,step=1+1)

In [28]:
one_to_ten

tensor([0, 2, 4, 6, 8])

In [29]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) #

In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [34]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [42]:
x_reshaped = x.reshape(1, 7,1,1,1)
x_reshaped, x_reshaped.shape, x_reshaped.view


(tensor([[[[[1.]]],
 
 
          [[[2.]]],
 
 
          [[[3.]]],
 
 
          [[[4.]]],
 
 
          [[[5.]]],
 
 
          [[[6.]]],
 
 
          [[[7.]]]]]), torch.Size([1, 7, 1, 1, 1]), <function Tensor.view>)

In [40]:
sqz = x_reshaped.squeeze()

In [41]:
sqz

tensor([1., 2., 3., 4., 5., 6., 7.])

In [43]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [44]:
x[:, 0]

tensor([[1, 2, 3]])

In [45]:
x[:, 0,1]

tensor([2])

In [46]:
import torch 
import random

In [47]:
import torch
import random


RANDOM_SEED=42 
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [48]:
!nvidia-smi

Sat Feb 11 15:10:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    26W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------